name: mini_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/

flutter_native_splash:
  color: "#42a5f5"
  image: assets/image/ # Path to your splash image
  android: true
  ios: true
  web: false
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
